AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Deployment for Capstone App

Resources:

  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: CapstoneCluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CapstoneTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: capstone-task
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: webapp-container
          Image: 827648152690.dkr.ecr.us-east-1.amazonaws.com/capstone-webapp:latest
          PortMappings:
            - ContainerPort: 80

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic to ECS tasks
      VpcId: vpc-008b20bfa7034d93e
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: CapstoneService
      Cluster: !Ref MyECSCluster
      TaskDefinition: !Ref MyTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-08f2cdecc903ae4fa
            - subnet-02a3acb567959eb99
          SecurityGroups:
            - !Ref MySecurityGroup